// <auto-generated />
namespace INMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Changeinorderscsfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changeinorderscsfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201912190717011_Change in orders csfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
