// <auto-generated />
namespace INMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class loginv101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loginv101));
        
        string IMigrationMetadata.Id
        {
            get { return "201912130912570_login-v1.01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
